"""initial_schema_with_enums

Revision ID: 664031ccf339
Revises: 
Create Date: 2026-03-10 22:38:17.333485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '664031ccf339'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_seat_categories_id'), table_name='seat_categories')
    op.drop_table('seat_categories')
    op.alter_column('bookings', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', name='bookingstatus'),
               nullable=False)
    op.alter_column('events', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('draft', 'published', 'cancelled', name='eventstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('payments', 'payment_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('success', 'failed', 'refunded', name='paymentstatus'),
               nullable=False)
    op.alter_column('seat_locks', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('locked', 'released', 'pending', 'confirmed', name='seatlockstatus'),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('seat_locks', 'status',
               existing_type=sa.Enum('locked', 'released', 'pending', 'confirmed', name='seatlockstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'payment_status',
               existing_type=sa.Enum('success', 'failed', 'refunded', name='paymentstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('events', 'status',
               existing_type=sa.Enum('draft', 'published', 'cancelled', name='eventstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', name='bookingstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_table('seat_categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('base_price', mysql.FLOAT(), nullable=True),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('seat_categories_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_seat_categories_id'), 'seat_categories', ['id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('threshold', mysql.FLOAT(), nullable=True),
    sa.Column('multiplier', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('pricing_rules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    # ### end Alembic commands ###
